#!/usr/bin/env python3
"""
Computes a mechanical, deterministic 0-100 "conviction_score" for every researched
stock in state.json, WITHOUT touching the existing categorical `conviction` field.

WHY THIS EXISTS
----------------
The categorical `conviction` field (Low/Low-Medium/Medium/Medium-High/High) is
pure per-stock LLM re-derivation every research run, with nothing mechanical to
check consistency against past calls. This has already caused two observed bugs:
(1) the same underlying situation - small-cap, weak trailing-average ROE, real
recent-quarter inflection - got classified differently across two different
stocks in two different runs; (2) an explicit "very-high trusted + no red flag
=> at least Medium-High" rule (see audit_state.py section 3.5) was violated
twice within the same session it was written, because there was no mechanical
scoring layer to check the LLM's output against.

`conviction_score` is a pure function of fields already sitting in state.json
(and trusted_users.json / a stock's own data/<slug>.json). It never calls an
LLM and never touches the network, so given the same state.json it always
produces the same number - useful as a cross-check against the categorical
field, and as a ranking signal that isn't subject to per-run drift.

FORMULA (see component docstrings below)
----------------------------------------------------------------------------------
  own_conviction = base_anchor          (0-44,  regraded categorical `conviction`)
                 + thesis_bonus         (0-20,  from `thesis_fit`)
                 + quality_lift         (-8..+10, from this stock's OWN quality_score)
                 + management_component (-12..+12, from data/<slug>.json `management_quality`)
                 - red_flag_penalty     (0 or 25, or forces the whole score to 0)

  trusted_lift   = trusted_signal_component            (-20..+24, SIGNED trusted-thread ledger)
                   but if negative, floored at -0.5 * max(own_conviction, 0)
                   -- one trusted user souring/exiting can HALVE the standalone
                      thesis at worst, never invert it.

  conviction_score = clamp(own_conviction + trusted_lift, 0, 100)
                     [forced to 0 for AVOID/EXCLUDE red_flag_tier regardless]

WHY THE own_conviction / trusted_lift SPLIT (2026-09-10, user-requested)
----------------------------------------------------------------------
"There should be a baseline conviction score for each stock generated by your
own analysis too, before topping it up with conviction from other trusted
users. There could be stocks that are good but no one else has understood but
you." Before this, `conviction_score` for a stock with no trusted signals was
just `base_anchor + thesis_bonus` (categorical label + thesis magnitude) - and
that was true for 43% of researched stocks. `own_conviction` now also carries a
`quality_lift` term straight off the stock's own mechanical `quality_score`
(ROCE/debt/FCF/margin/capex), so a genuinely high-quality business scores well
on its own merit with zero forum corroboration. The breakdown reports
`own_conviction` and `trusted_lift` as separate line items so it's always
visible how much of a name's conviction is standalone vs borrowed.

`quality_lift` DOES overlap `quality_score`'s own 0.25 weight in master_score,
but only mildly: it's ±8..10 on a 0-100 conviction_score that is itself 0.25 of
master_score, i.e. ~2-3 effective master-score points. Deliberate and bounded -
a great business SHOULD read as both "high quality" and "high own-conviction".

Max own_conviction is 44+20+10+12 = 86; + trusted_lift 24 -> clamp 100.

TRUSTED_SIGNAL_COMPONENT (redesigned 2026-09-10)
-----------------------------------------------
Replaces the old `trust_component` (0-25, read only the single
`trusted_conviction_strength`/`_source_user` scalars on the state entry) +
`corroboration_bonus` (0-15, a flat cliff at 2 / 3+ distinct users). Those two
had three flaws the user called out: (a) they only ever ADDED - an exit or a
year-old call could never pull a score DOWN; (b) the flat corroboration cliff
plus the SKILL's separate "+1 categorical notch per qualifying mention" meant
N trusted users mentioning a stock once each could ratchet the score up almost
without bound; (c) recency was a 0.15 pass/fail gate, not a continuous decay.

The new component reads data/<slug>.json `trusted_signals[]` as the whole
ledger and is a pure function of it:

  per signal:
    w      = recency_weight.weight_for_date(signal.date)   # 1.0 / 0.6 / 0.25 / 0.05
    smult  = {very-high: 1.0, high: 0.5, else: 0.4}[signal.strength]
    tmult  = {core: 1.0, elevated: 0.5, unknown: 0.45}[trust_tier(signal.username)]
    superseded (and not an exit)          -> contributes 0 (replaced by a newer entry)
    signal_type in (exit, sell, sold)     -> NEGATIVE: TS_EXIT_BASE * smult * tmult * w
    signal_type in (trim, reduce)         -> NEGATIVE: TS_EXIT_BASE * TS_TRIM_FACTOR * smult * tmult * w
    otherwise (conviction / add / reiterate / None)
                                          -> POSITIVE: TS_POS_BASE * smult * tmult * w

  positives: sort desc, sum with GEOMETRIC diminishing returns
             pos = Σ c_i * TS_DIMINISH**i     (1st mention full, 2nd *0.55, 3rd *0.30 ...)
             so the marginal value of the 4th distinct trusted voice is < 2 pts.
  negatives: summed LINEARLY (exits stack), magnitude capped at TS_NEG_CAP.
  component = clamp(pos_capped - neg_capped, -TS_NEG_CAP, TS_POS_CAP)

Fallback: 71 older `source: "trusted-thread"` entries carry a
`trusted_conviction_strength` scalar on state but have NO ledger file yet
(written by `vpscreen-scan`, a different task/convention). For those, one
synthetic positive is added, recency-approximated from
`trusted_conviction_floor_active` (True -> 0.6, False -> 0.25, absent -> 0.4),
so removing the old scalar path doesn't silently zero them out - but a real
dated ledger entry is always worth more than the fallback.

Consequences that are INTENDED, not bugs:
  * a stock a trusted user tried and then EXITED can score below an untouched
    peer (fresh core exit ~ -9), and that penalty then decays with the exit
    post's age just like a positive call does.
  * a `very-high` tag with no forum re-touch for a year fades toward ~0 on its
    own, every run, with no audit needed.
  * the categorical `conviction` label is NO LONGER notched by trusted
    mentions at all (SKILL Step 3.3 rewritten). The only mechanical categorical
    floor is audit_state.py 3.5 (core-tier + recent + very-high + no red flag
    => >= Medium-High), which is unchanged and still feeds base_anchor here. `management_component` is TVGP's "P" (promoter/management
quality as a POSITIVE attribute, not just red-flag absence - see
playbook/ishmohit-soic-style.md); it is GUARDED - exactly 0 whenever a stock's
data file has no `management_quality` block, so it is a strict no-op on the
whole registry until `deepdive-top100` starts populating that block. In
practice almost nothing hits the ceiling, which is fine for a ranking signal
(relative ordering matters more than absolute calibration).

USAGE
-----
    python3 compute_conviction_score.py        (from scripts/ or project root)

Writes:
  - state.json:  adds/overwrites `conviction_score` on every stock entry that
    has status in ("researched", "excluded", "avoid") - i.e. has actually been
    through research, not a bare "candidate". Leaves `conviction` untouched.
    Candidates (no research done yet) are left without a conviction_score key
    entirely, since there is nothing to score.
  - data/conviction-scores.json: sorted (descending) ranked report list.

NOTE ON A CONCURRENT AGENT'S WORK
----------------------------------
Another agent is (or may be, depending on timing) landing a shared
`scripts/recency_weight.py` module (function `weight_for_date(date_str,
today=None) -> float`) and a `trusted_conviction_floor_active` field on stock
entries, plus a `trust_tier` field ("core"/"elevated") on trusted_users.json
entries. This script:
  - imports `recency_weight.weight_for_date` if the module exists;
  - otherwise falls back to an inline implementation with the identical
    signature (see `_fallback_weight_for_date` below), which should be
    DELETED and replaced with the real import once scripts/recency_weight.py
    lands for real - it's a heuristic stand-in, not a permanent fixture.
  - already found `trust_tier` present on trusted_users.json (see component 4).
  - did NOT find `trusted_conviction_floor_active` or
    `trusted_conviction_source_user` present on any state.json stock entry as
    of this run - both are handled defensively (treated as absent -> neutral/
    full-weight default) so this script keeps working once they do land.
"""
import datetime
import json
import os
import re
import sys

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATE_PATH = os.path.join(BASE, "state.json")
TRUSTED_USERS_PATH = os.path.join(BASE, "trusted_users.json")
DATA_DIR = os.path.join(BASE, "data")
OUT_PATH = os.path.join(BASE, "data", "conviction-scores.json")

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from resolve_data_file import resolve_data_path  # noqa: E402

RESEARCHED_STATUSES = ("researched", "excluded", "avoid")

# --- component 1: base conviction anchor (0-44) ------------------------------
# This is the single most important OWN-ANALYSIS input - the per-research-run
# categorical judgment, no longer notched by trusted mentions (see 2026-09-10
# redesign). Regraded 2026-09-10: the BOTTOM two buckets are unchanged (8/16) -
# a low own-conviction call should stay low, and any drop those names see comes
# from losing a stale unverified trust prop, not from the anchor. Only the TOP
# is widened (25/35/45 was 24/32/40) so a genuine standalone High / Medium-High
# call carries real weight even with zero forum corroboration.
CONVICTION_ANCHOR = {
    "Low": 8,
    "Low-Medium": 16,
    "Medium": 25,
    "Medium-High": 35,
    "High": 45,
}

# --- component 2: thesis-fit magnitude bonus (0-20) ---------------------------
THESIS_BONUS = {
    "100x-in-10-years": 20,
    "10x-in-2-3-years": 14,
    "neither": 0,
}

# --- component 2b: own-quality lift (-8 .. +10) -----------------------------
# Own-analysis term, user-requested 2026-09-10: a stock's OWN mechanical
# quality_score (data/quality-scores.json / state.json, from ROCE/debt/FCF/
# margin/capex - see QUALITY_SCORE_METHODOLOGY.md) lifts or drags its
# own_conviction independently of any trusted signal. GUARDED: exactly 0 when
# quality_score is absent (only ~195 of 678 researched stocks have it yet), so
# it's a no-op until deepdive-top100 populates it - same pattern as
# management_component. Centered at 50 (registry median ~48). ASYMMETRIC clamp:
# the point of this term is to REWARD a high-quality business others haven't
# noticed (+10 upside); the downside is capped tighter (-5) because (a) genuinely
# bad businesses are already handled by red_flag_tier and the low categorical
# anchor, and (b) quality_score is structurally unkind to lenders/financials
# (ROCE/debt/FCF), which shouldn't be double-penalised here.
QUALITY_LIFT_CENTER = 50.0
QUALITY_LIFT_SLOPE = 0.25
QUALITY_LIFT_MIN = -5.0
QUALITY_LIFT_MAX = 10.0

# negative trusted_lift is floored at this fraction of own_conviction:
TRUSTED_LIFT_NEG_FLOOR_FRAC = 0.5

# --- component 3: red-flag penalty --------------------------------------------
RED_FLAG_PENALTY = 25           # "HIGH CAUTION" - positive magnitude, subtracted below
RED_FLAG_ZERO = {"AVOID", "EXCLUDE"}   # forces whole score to 0

# --- component 4: trusted-signal ledger (recency-weighted, SIGNED) -----------
# See the module docstring's TRUSTED_SIGNAL_COMPONENT section for the rationale.
# All five are deliberately tunable knobs - the STRUCTURE (signed, per-signal
# recency decay, geometric diminishing) is the fix; these numbers just set the
# magnitude. Calibrated 2026-09-10 against the live ledger (see methodology doc).
TS_POS_BASE = 15.0          # a single fresh core very-high positive call
TS_EXIT_BASE = 10.0         # a single fresh core very-high exit (negative)
TS_STRENGTH_MULT = {"very-high": 1.0, "high": 0.5}
TS_STRENGTH_DEFAULT = 0.4   # strength missing / unrecognized
TS_TIER_MULT = {"core": 1.0, "elevated": 0.55}
TS_TIER_DEFAULT = 0.45      # username not resolvable in trusted_users.json
TS_TRIM_FACTOR = 0.4        # a "trim" is a fractional exit
TS_DIMINISH = 0.62          # geometric decay across DISTINCT trusted voices (i-th, i from 0)
TS_REPEAT_KICKER = 0.15     # per extra mention BY THE SAME USER, as a fraction of their strongest
TS_REPEAT_KICKER_CAP = 0.30 # ... capped: one person repeating themselves tops out at +30%
TS_POS_CAP = 24.0
TS_NEG_CAP = 20.0           # magnitude cap on the summed negatives
# keyed on trusted_conviction_floor_active for the no-ledger fallback path:
TS_FALLBACK_WEIGHT = {True: 0.6, False: 0.25, None: 0.4}
# an exit/trim is only ever recognised from an EXPLICIT signal_type field -
# never sniffed from free-text notes (that misfired on "Sold out Zen ...,
# entered Satin" - a BUY of Satin whose note happens to contain "sold out").
TS_EXIT_TYPES = {"exit", "sell", "sold", "exited"}
TS_TRIM_TYPES = {"trim", "reduce", "reduced", "trimmed"}
# recency weight below which a positive signal no longer counts toward the
# distinct-trusted-user tally reported in the breakdown (scoring still uses its
# real, tiny weight - this bar is only for the human-facing count).
CORROBORATION_RECENCY_MIN_WEIGHT = 0.15

# --- component 6: management quality (-12 .. +12) ----------------------------
# TVGP's "P" (playbook/ishmohit-soic-style.md) - promoter/management quality as a
# POSITIVE attribute. Read from data/<slug>.json's `management_quality` block
# (scripts/ISHMOHIT_SIGNALS_SCHEMA.md). GUARDED: returns exactly 0 when the block
# is absent, so this is a strict no-op on every stock until deepdive-top100
# populates the block. Widened 2026-09-04 (user-requested) to also score
# capital-allocation discipline, related-party-transaction trend, and
# dividend/buyback discipline - previously rpt_trend was collected on every
# block but never actually scored, and there was no field at all for capital
# allocation or shareholder returns. Each of the 5 sub-terms no-ops (0) on its
# own if missing/unclear, so a block with only the original 2 fields scores
# identically to before this widen - the new terms are additive.
MGMT_ASSESSMENT_PTS = {"positive": 6, "neutral": 0, "concern": -6}
MGMT_GUIDANCE_PTS = {
    "reliable": 2, "mixed": 0, "over-promises": -4,
    "no-track-record": 0, "unclear": 0,
}
MGMT_CAPITAL_ALLOC_PTS = {"disciplined": 3, "neutral": 0, "value-destructive": -4}
MGMT_RPT_PTS = {"clean": 2, "flat": 1, "rising": -2, "concerning": -5}
MGMT_SHAREHOLDER_RETURNS_PTS = {"consistent": 2, "initiated": 1, "none": 0, "erratic": -3}
MGMT_COMPONENT_CLAMP = 12

# (old "component 5: multi-user corroboration bonus" removed 2026-09-10 - its
# job is now done, continuously and with diminishing returns, inside the signed
# trusted_signal_component; see the module docstring.)


# ------------------------------------------------------------------------------
# recency_weight: prefer the shared module if the other concurrent agent's
# work has landed; otherwise fall back to an inline heuristic with the same
# signature. DELETE this fallback once scripts/recency_weight.py is real.
# ------------------------------------------------------------------------------
_recency_module_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "recency_weight.py")
if os.path.exists(_recency_module_path):
    sys.path.insert(0, os.path.dirname(_recency_module_path))
    from recency_weight import weight_for_date  # noqa: E402
    _USING_SHARED_RECENCY_MODULE = True
else:
    _USING_SHARED_RECENCY_MODULE = False

    def _fallback_weight_for_date(date_str, today=None):
        """
        Heuristic stand-in for the shared recency_weight.weight_for_date().
        trusted_signals[].date in this project is messy free text, not
        reliably ISO dates, so this does best-effort extraction:
          - explicit ISO date/month ("2026-08-15", "2026-08") -> real decay
            (~1-year half-life exponential decay from `today`)
          - text containing "recent"/"ongoing"/"current" (no explicit stale
            marker) -> high weight (0.85), it's asserted to be fresh
          - text containing "backfill" with no other recency marker -> lower
            weight (0.4), it's explicitly a retroactive/backfilled note
          - a bare 4-digit year found anywhere -> decay from Jan 1 of that year
          - empty/None/unparseable -> neutral default (0.5), conservative but
            not zero (we don't want to silently drop genuine signals just
            because the date field is messy prose)
        Returns a float in [0.0, 1.0].
        """
        if not date_str:
            return 0.5
        if today is None:
            today = datetime.date.today()
        s = date_str.strip().lower()

        iso_match = re.search(r"(\d{4})-(\d{2})(?:-(\d{2}))?", s)
        if iso_match:
            y, m, d = iso_match.groups()
            try:
                dt = datetime.date(int(y), int(m), int(d) if d else 1)
                age_days = max(0, (today - dt).days)
                return round(0.5 ** (age_days / 365.0), 4)
            except ValueError:
                pass

        if any(k in s for k in ("recent", "ongoing", "current")):
            return 0.85

        if "backfill" in s:
            return 0.4

        year_match = re.search(r"(20\d{2})", s)
        if year_match:
            try:
                dt = datetime.date(int(year_match.group(1)), 1, 1)
                age_days = max(0, (today - dt).days)
                return round(0.5 ** (age_days / 365.0), 4)
            except ValueError:
                pass

        return 0.5

    weight_for_date = _fallback_weight_for_date


def clamp(x, lo, hi):
    return max(lo, min(hi, x))


def load_json(path, default=None):
    if not os.path.exists(path):
        return default
    with open(path) as f:
        return json.load(f)


def compute_base_anchor(conviction):
    return CONVICTION_ANCHOR.get(conviction, 0)


def compute_thesis_bonus(thesis_fit):
    return THESIS_BONUS.get(thesis_fit, 0)


def compute_quality_lift(entry):
    """(-8 .. +10) own-analysis lift from the stock's own mechanical
    `quality_score` on the state entry. Exactly 0.0 when quality_score is
    absent/None (a strict no-op until deepdive-top100 populates it)."""
    qs = entry.get("quality_score")
    if qs is None:
        return 0.0
    try:
        qs = float(qs)
    except (TypeError, ValueError):
        return 0.0
    return round(clamp((qs - QUALITY_LIFT_CENTER) * QUALITY_LIFT_SLOPE,
                       QUALITY_LIFT_MIN, QUALITY_LIFT_MAX), 2)


def compute_red_flag_penalty(red_flag_tier):
    """Returns (penalty_points, force_zero). penalty_points is a positive
    magnitude to be SUBTRACTED from the raw score (0 = no penalty)."""
    if not red_flag_tier:  # None or "" both mean "no red flag" in this data
        return 0, False
    if red_flag_tier in RED_FLAG_ZERO:
        return 0, True
    if red_flag_tier == "HIGH CAUTION":
        return RED_FLAG_PENALTY, False
    # Unrecognized non-empty value: treat conservatively as HIGH CAUTION-
    # equivalent rather than ignoring it silently, and flag it in the report.
    return RED_FLAG_PENALTY, False


def _trust_tier_mult(username, trusted_users):
    if username and trusted_users:
        ue = trusted_users.get(username)
        if ue:
            return TS_TIER_MULT.get(ue.get("trust_tier"), TS_TIER_DEFAULT)
    return TS_TIER_DEFAULT


def _classify_signal(sig):
    """Return one of 'positive' | 'exit' | 'trim' | 'skip' for a trusted_signals
    entry. `skip` = a superseded entry that isn't an explicit exit (it's just
    been replaced by a newer entry from the same user - neutral, not negative)."""
    stype = (sig.get("signal_type") or sig.get("type") or "").strip().lower()
    # An EXPLICIT exit/trim type wins even over `superseded` (an exit entry may
    # itself be marked superseded by a still-later note from the same user).
    if stype in TS_EXIT_TYPES:
        return "exit"
    if stype in TS_TRIM_TYPES:
        return "trim"
    # Everything else: a superseded entry is neutral (it's been replaced by a
    # newer entry from the same user), anything current is a positive. We do NOT
    # try to infer an exit from note text - that is unreliable.
    if sig.get("superseded"):
        return "skip"
    return "positive"


def compute_trusted_signal_component(slug, entry, trusted_users, today=None, warnings=None):
    """Signed, recency-weighted trusted-thread component (see module docstring).
    Returns (component_float, detail_dict)."""
    pos_by_user = {}           # username (or "" for anon) -> list of per-signal floats
    neg_total = 0.0
    n_pos_signals = 0
    n_exit = n_trim = 0
    used_ledger = False

    def _add_pos(contrib, username):
        pos_by_user.setdefault(username or "", []).append(contrib)

    data_path = resolve_data_path(BASE, DATA_DIR, slug)
    signals = None
    if os.path.exists(data_path):
        try:
            with open(data_path) as f:
                signals = json.load(f).get("trusted_signals")
        except (json.JSONDecodeError, OSError):
            signals = None

    # ~95% of existing ledger entries predate the per-signal `strength` field
    # (it's written by this SKILL's Step 3.3 going forward, not by the older
    # vpscreen-scan convention). Fall back to the state entry's
    # `trusted_conviction_strength` scalar so those aren't all flattened to the
    # weak default.
    entry_strength = entry.get("trusted_conviction_strength")

    if isinstance(signals, list) and signals:
        used_ledger = True
        for sig in signals:
            if not isinstance(sig, dict):
                continue
            kind = _classify_signal(sig)
            if kind == "skip":
                continue
            username = sig.get("username") or sig.get("user")
            w = weight_for_date(sig.get("date"), today=today)
            smult = TS_STRENGTH_MULT.get(sig.get("strength") or entry_strength, TS_STRENGTH_DEFAULT)
            tmult = _trust_tier_mult(username, trusted_users)
            if kind == "positive":
                _add_pos(TS_POS_BASE * smult * tmult * w, username)
                n_pos_signals += 1
            elif kind == "exit":
                neg_total += TS_EXIT_BASE * smult * tmult * w
                n_exit += 1
            elif kind == "trim":
                neg_total += TS_EXIT_BASE * TS_TRIM_FACTOR * smult * tmult * w
                n_trim += 1
    elif entry.get("source") == "trusted-thread" and entry.get("trusted_conviction_strength"):
        # no-ledger fallback: synthesize ONE positive from the state scalars,
        # recency-approximated from trusted_conviction_floor_active.
        smult = TS_STRENGTH_MULT.get(entry.get("trusted_conviction_strength"), TS_STRENGTH_DEFAULT)
        tmult = _trust_tier_mult(entry.get("trusted_conviction_source_user"), trusted_users)
        w = TS_FALLBACK_WEIGHT.get(entry.get("trusted_conviction_floor_active"), 0.4)
        _add_pos(TS_POS_BASE * smult * tmult * w, entry.get("trusted_conviction_source_user"))
        n_pos_signals += 1

    # Collapse to ONE score per distinct voice: a user's strongest call at full
    # weight + a small kicker for having repeated it (repetition by one person is
    # worth far less than a second independent person). THEN apply geometric
    # diminishing returns across the distinct voices - so neither "many users,
    # one mention each" nor "one user, many mentions" can run the score away.
    per_user_scores = []
    for uname, contribs in pos_by_user.items():
        contribs.sort(reverse=True)
        if uname == "":
            per_user_scores.extend(contribs)          # anon: each counts as its own voice
        else:
            kicker = min(TS_REPEAT_KICKER_CAP, TS_REPEAT_KICKER * (len(contribs) - 1))
            per_user_scores.append(contribs[0] * (1.0 + kicker))
    per_user_scores.sort(reverse=True)
    pos = sum(c * (TS_DIMINISH ** i) for i, c in enumerate(per_user_scores))

    pos_capped = min(pos, TS_POS_CAP)
    neg_capped = min(neg_total, TS_NEG_CAP)
    component = clamp(round(pos_capped - neg_capped, 2), -TS_NEG_CAP, TS_POS_CAP)

    distinct_users = sum(1 for u in pos_by_user if u != "")
    detail = {
        "value": component,
        "pos_raw": round(pos, 2),
        "pos_capped": round(pos_capped, 2),
        "neg_raw": round(neg_total, 2),
        "neg_capped": round(neg_capped, 2),
        "n_positive_signals": n_pos_signals,
        "n_exit_signals": n_exit,
        "n_trim_signals": n_trim,
        "distinct_trusted_users": distinct_users,
        "source": "ledger" if used_ledger else ("fallback-scalar" if n_pos_signals else "none"),
    }
    return component, detail


def compute_management_component(slug, warnings=None):
    """(-12..+12) from data/<slug>.json's `management_quality` block; 0 if the block
    is absent or the file is unreadable (the guard that makes this a no-op until
    deepdive-top100 populates it). 5 sub-terms (assessment, guidance_credibility,
    capital_allocation_track_record, rpt_trend, shareholder_returns), each an
    independent no-op (0) when its field is missing/unclear. Returns
    (component_float, detail_dict_or_None)."""
    data_path = resolve_data_path(BASE, DATA_DIR, slug)
    if not os.path.exists(data_path):
        return 0.0, None
    try:
        with open(data_path) as f:
            stock_data = json.load(f)
    except (json.JSONDecodeError, OSError):
        return 0.0, None

    mq = stock_data.get("management_quality")
    if not isinstance(mq, dict):
        return 0.0, None

    assessment = mq.get("assessment")
    guidance = mq.get("guidance_credibility")
    capital_alloc = mq.get("capital_allocation_track_record")
    rpt = mq.get("rpt_trend")
    shareholder_returns = mq.get("shareholder_returns")

    a_pts = MGMT_ASSESSMENT_PTS.get(assessment)
    if a_pts is None:
        if warnings is not None and assessment is not None:
            warnings.append((slug, f"unrecognized management_quality.assessment {assessment!r} -> 0"))
        a_pts = 0
    g_pts = MGMT_GUIDANCE_PTS.get(guidance, 0)

    ca_pts = MGMT_CAPITAL_ALLOC_PTS.get(capital_alloc)
    if ca_pts is None:
        if warnings is not None and capital_alloc is not None and capital_alloc != "unclear":
            warnings.append((slug, f"unrecognized management_quality.capital_allocation_track_record {capital_alloc!r} -> 0"))
        ca_pts = 0

    rpt_pts = MGMT_RPT_PTS.get(rpt)
    if rpt_pts is None:
        if warnings is not None and rpt is not None and rpt != "unclear":
            warnings.append((slug, f"unrecognized management_quality.rpt_trend {rpt!r} -> 0"))
        rpt_pts = 0

    sr_pts = MGMT_SHAREHOLDER_RETURNS_PTS.get(shareholder_returns)
    if sr_pts is None:
        if warnings is not None and shareholder_returns is not None and shareholder_returns != "unclear":
            warnings.append((slug, f"unrecognized management_quality.shareholder_returns {shareholder_returns!r} -> 0"))
        sr_pts = 0

    comp = clamp(a_pts + g_pts + ca_pts + rpt_pts + sr_pts, -MGMT_COMPONENT_CLAMP, MGMT_COMPONENT_CLAMP)
    return float(comp), {
        "assessment": assessment,
        "guidance_credibility": guidance,
        "capital_allocation_track_record": capital_alloc,
        "rpt_trend": rpt,
        "shareholder_returns": shareholder_returns,
    }


def compute_score_for_entry(slug, entry, trusted_users, today=None, warnings=None):
    base_anchor = compute_base_anchor(entry.get("conviction"))
    thesis_bonus = compute_thesis_bonus(entry.get("thesis_fit"))
    quality_lift = compute_quality_lift(entry)
    red_flag_penalty, force_zero = compute_red_flag_penalty(entry.get("red_flag_tier"))
    trusted_signal_component, trusted_signal_detail = compute_trusted_signal_component(
        slug, entry, trusted_users, today=today, warnings=warnings)
    management_component, management_detail = compute_management_component(slug, warnings=warnings)

    # --- own-analysis baseline: everything I concluded about this stock myself,
    #     with NO trusted-forum input. red_flag_penalty is a positive magnitude.
    own_conviction = round(base_anchor + thesis_bonus + quality_lift
                           + management_component - red_flag_penalty, 2)

    # --- trusted top-up: a NEGATIVE trusted_lift (a trusted user souring/exiting)
    #     can drag the score down, but is floored so it can't more than halve a
    #     genuine standalone thesis or invert it.
    trusted_lift = trusted_signal_component
    neg_floor_applied = False
    if trusted_lift < 0 and own_conviction > 0:
        floor = -TRUSTED_LIFT_NEG_FLOOR_FRAC * own_conviction
        if trusted_lift < floor:
            trusted_lift = floor
            neg_floor_applied = True
    trusted_lift = round(trusted_lift, 2)

    if force_zero:
        score = 0.0
    else:
        score = clamp(round(own_conviction + trusted_lift, 2), 0, 100)

    breakdown = {
        "own_conviction": own_conviction,
        "trusted_lift": trusted_lift,
        "base_anchor": base_anchor,
        "thesis_bonus": thesis_bonus,
        "quality_lift": quality_lift,
        "management_component": round(management_component, 2),
        "red_flag_penalty": red_flag_penalty,
        "red_flag_forced_zero": force_zero,
        "trusted_signal_component": round(trusted_signal_component, 2),  # pre-floor, back-compat
        "trusted_lift_neg_floor_applied": neg_floor_applied,
        "trusted_signal_detail": trusted_signal_detail,
        "distinct_trusted_users": trusted_signal_detail["distinct_trusted_users"],
        "management_quality": management_detail,
    }
    return score, breakdown


def main():
    state = load_json(STATE_PATH)
    if state is None:
        print(f"ERROR: {STATE_PATH} not found", file=sys.stderr)
        sys.exit(1)
    stocks = state.get("stocks", {})

    trusted_users_raw = load_json(TRUSTED_USERS_PATH, default={})
    trusted_users = trusted_users_raw.get("users", {}) if trusted_users_raw else {}

    today = datetime.date.today()

    unrecognized_red_flags = []
    mgmt_warnings = []
    scored = []
    skipped_not_researched = 0

    for slug, entry in stocks.items():
        if entry.get("status") not in RESEARCHED_STATUSES:
            skipped_not_researched += 1
            continue

        rft = entry.get("red_flag_tier")
        if rft and rft not in RED_FLAG_ZERO and rft != "HIGH CAUTION":
            unrecognized_red_flags.append((slug, rft))

        score, breakdown = compute_score_for_entry(
            slug, entry, trusted_users, today=today, warnings=mgmt_warnings
        )
        entry["conviction_score"] = score

        # write the own/trusted split onto the state entry too - downstream
        # consumers (deepdive queue, guidance backlog, confluence100) can then
        # see how much of a name's conviction is standalone.
        entry["own_conviction_score"] = breakdown["own_conviction"]
        entry["trusted_lift"] = breakdown["trusted_lift"]

        scored.append({
            "slug": slug,
            "name": entry.get("name"),
            "conviction_score": score,
            "own_conviction": breakdown["own_conviction"],
            "trusted_lift": breakdown["trusted_lift"],
            "conviction": entry.get("conviction"),
            "thesis_fit": entry.get("thesis_fit"),
            "quality_score": entry.get("quality_score"),
            "market_cap_tier": entry.get("market_cap_tier"),
            "red_flag_tier": entry.get("red_flag_tier"),
            "source": entry.get("source"),
            "score_breakdown": breakdown,
        })

    scored.sort(key=lambda r: r["conviction_score"], reverse=True)

    with open(STATE_PATH, "w") as f:
        json.dump(state, f, indent=2)

    with open(OUT_PATH, "w") as f:
        json.dump(scored, f, indent=2)

    print(f"=== compute_conviction_score.py ===")
    print(f"recency_weight source: {'shared scripts/recency_weight.py' if _USING_SHARED_RECENCY_MODULE else 'inline fallback (swap for shared module once it lands)'}")
    print(f"scored {len(scored)} researched-status stocks ({skipped_not_researched} candidates skipped, no research yet)")
    if unrecognized_red_flags:
        print(f"WARNING: {len(unrecognized_red_flags)} unrecognized red_flag_tier values treated as HIGH CAUTION-equivalent (-25): {unrecognized_red_flags}")
    if mgmt_warnings:
        print(f"WARNING: {len(mgmt_warnings)} unrecognized management_quality.assessment values treated as 0:")
        for slug, msg in mgmt_warnings[:20]:
            print(f"  {slug}: {msg}")
    n_mgmt = sum(1 for r in scored if r["score_breakdown"].get("management_quality"))
    print(f"management_component active on {n_mgmt}/{len(scored)} scored stocks "
          f"(0 = block not yet populated by deepdive-top100; a no-op until then)")
    tsd = [r["score_breakdown"].get("trusted_signal_detail") or {} for r in scored]
    n_ledger = sum(1 for d in tsd if d.get("source") == "ledger")
    n_fallback = sum(1 for d in tsd if d.get("source") == "fallback-scalar")
    n_neg = sum(1 for r in scored if (r["score_breakdown"].get("trusted_signal_component") or 0) < 0)
    n_exit = sum(d.get("n_exit_signals", 0) for d in tsd)
    print(f"trusted_signal_component: {n_ledger} scored off a dated ledger, {n_fallback} off the "
          f"no-ledger scalar fallback; {n_neg} stocks currently NET-NEGATIVE on trusted signals "
          f"({n_exit} exit signal(s) in the data)")
    n_qlift = sum(1 for r in scored if r["score_breakdown"].get("quality_lift"))
    n_standalone = sum(1 for r in scored if r["score_breakdown"].get("trusted_lift", 0) == 0)
    n_floored = sum(1 for r in scored if r["score_breakdown"].get("trusted_lift_neg_floor_applied"))
    own = [r["score_breakdown"]["own_conviction"] for r in scored]
    print(f"own_conviction (base_anchor + thesis + quality_lift + mgmt - red_flag): "
          f"mean {sum(own)/len(own):.1f}, range {min(own):.1f}..{max(own):.1f}; "
          f"quality_lift active on {n_qlift}/{len(scored)}; "
          f"{n_standalone} stocks score purely on own analysis (trusted_lift == 0); "
          f"{n_floored} had a negative trusted_lift floored at -50% of own_conviction")
    print(f"wrote conviction_score (+ own_conviction_score, trusted_lift) into {STATE_PATH}")
    print(f"wrote ranked report to {OUT_PATH}")
    print()
    print(f"{'score':>6} {'=own':>6} {'+trust':>7}   slug (categorical / thesis)")
    print("Top 10:")
    for r in scored[:10]:
        b = r["score_breakdown"]
        print(f"  {r['conviction_score']:6.2f} {b['own_conviction']:6.1f} {b['trusted_lift']:+7.1f}   {r['slug']:46s} ({r['conviction']}, {r['thesis_fit']})")
    print("Bottom 5:")
    for r in scored[-5:]:
        b = r["score_breakdown"]
        print(f"  {r['conviction_score']:6.2f} {b['own_conviction']:6.1f} {b['trusted_lift']:+7.1f}   {r['slug']:46s} ({r['conviction']}, {r['thesis_fit']}, rf={r['red_flag_tier']})")


if __name__ == "__main__":
    main()
